# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "clientdatas", :force => true do |t|
    t.column "ClusterName",  :string, :limit => 50
    t.column "ShopName",     :string
    t.column "Date",         :date
    t.column "GroupID",      :string
    t.column "MachineNo",    :string
    t.column "MachineName",  :string
    t.column "ScreenIN",     :string
    t.column "ScreenOUT",    :string
    t.column "MeterIN",      :string
    t.column "MeterOUT",     :string
    t.column "Machineshort", :string
    t.column "Shortreason",  :string
    t.column "status",       :string,               :default => "0", :null => false
    t.column "Created_Time", :time
  end

  add_index "clientdatas", ["Date"], :name => "Date"
  add_index "clientdatas", ["ClusterName", "ShopName", "GroupID", "MachineNo", "status"], :name => "ClusterName"
  add_index "clientdatas", ["Created_Time"], :name => "Created_Time"

  create_table "clusters", :force => true do |t|
    t.column "ClusterName", :string
  end

  create_table "config", :force => true do |t|
    t.column "NoofHours",       :integer, :default => 18
    t.column "FilesFolderPath", :string,  :default => "C://data"
  end

  create_table "configurations", :force => true do |t|
    t.column "noofhours",        :integer
    t.column "FilesFolderPath",  :string,   :limit => 100, :default => "C:/data"
    t.column "BackupFolderPath", :string,   :limit => 100, :default => "C:/backup"
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "countercollections", :force => true do |t|
    t.column "ClusterName", :string
    t.column "ShopName",    :string
    t.column "Date",        :date
    t.column "Cash",        :integer
    t.column "Exp",         :integer
    t.column "HC",          :integer
    t.column "Credit",      :integer
    t.column "Short_Ext",   :integer
    t.column "Openingbal",  :integer
    t.column "KEY1",        :integer
    t.column "KEY2",        :integer
    t.column "KEY3",        :integer
    t.column "KEY4",        :integer
    t.column "Outstanding", :integer
    t.column "status",      :string,  :default => "0"
    t.column "Total",       :integer
  end

  create_table "counterdatas", :force => true do |t|
    t.column "ClusterName", :string
    t.column "ShopName",    :string
    t.column "Date",        :date
    t.column "Cash",        :integer, :default => 0
    t.column "Exp",         :integer, :default => 0
    t.column "HC",          :integer, :default => 0
    t.column "Credit",      :integer, :default => 0
    t.column "Short_Ext",   :integer, :default => 0
    t.column "Openingbal",  :integer, :default => 0
    t.column "KEY1",        :integer, :default => 0
    t.column "KEY2",        :integer, :default => 0
    t.column "KEY3",        :integer, :default => 0
    t.column "KEY4",        :integer, :default => 0
    t.column "Outstanding", :integer, :default => 0
    t.column "status",      :string,  :default => "0", :null => false
    t.column "Total",       :integer, :default => 0
  end

  create_table "groups", :force => true do |t|
    t.column "ShopID",      :string
    t.column "ShopName",    :string
    t.column "GroupID",     :string, :limit => 222
    t.column "ClusterName", :string, :limit => 222
  end

  create_table "machinedatas", :force => true do |t|
    t.column "TRANS_DATE",      :date
    t.column "T_DATE",          :string,  :limit => 50
    t.column "CLUSTER_NAME",    :string,  :limit => 50
    t.column "SHOP_NAME",       :string,  :limit => 50
    t.column "GROUP_ID",        :string,  :limit => 20
    t.column "MACHINE_NO",      :string,  :limit => 20
    t.column "MACHINE_NAME",    :string,  :limit => 30
    t.column "SCREEN_RATE_IN",  :integer,               :default => 0
    t.column "SCREEN_RATE_OUT", :integer,               :default => 0
    t.column "MTR_RATE_IN",     :integer,               :default => 0
    t.column "MTE_RATE_OUT",    :integer,               :default => 0
    t.column "MULTIPLY_BY",     :integer,               :default => 0
    t.column "SRIN",            :float,                 :default => 0.0
    t.column "SROUT",           :float,                 :default => 0.0
    t.column "SRPER",           :string,  :limit => 30, :default => "0"
    t.column "PSRINVALUE",      :float,                 :default => 0.0
    t.column "PSROUTVALUE",     :float,                 :default => 0.0
    t.column "MTRIN",           :float,                 :default => 0.0
    t.column "MTROUT",          :float,                 :default => 0.0
    t.column "MTRPER",          :string,  :limit => 12, :default => "0"
    t.column "PMTRINVALUE",     :float,                 :default => 0.0
    t.column "PMTROUTVALUE",    :float,                 :default => 0.0
    t.column "TSRIN",           :float,                 :default => 0.0
    t.column "TSROUT",          :float,                 :default => 0.0
    t.column "MTRSHORT",        :integer,               :default => 0
    t.column "SHORTREASON",     :string,  :limit => 30
    t.column "SRCOLL",          :integer,               :default => 0
    t.column "CALCULATEBY",     :string,  :limit => 20, :default => "0"
    t.column "SETTING",         :string
    t.column "LASTSETTING",     :string,                :default => "A"
    t.column "LASTPER",         :string,  :limit => 20, :default => "0"
    t.column "TMTRIN",          :float,                 :default => 0.0
    t.column "TMTROUT",         :float,                 :default => 0.0
    t.column "MTRCOLL",         :float,                 :default => 0.0
    t.column "MTRDIFFIN",       :float,                 :default => 0.0
    t.column "MTRDIFFOUT",      :float,                 :default => 0.0
    t.column "MTRDIFFWHY",      :string,  :limit => 30
    t.column "TSRPER",          :string,  :limit => 20, :default => "0"
    t.column "TMTRPER",         :string,  :limit => 20, :default => "0"
    t.column "THIRTYDAYSAVG",   :float,                 :default => 0.0
    t.column "TENDAYSAVG",      :float,                 :default => 0.0
    t.column "SRAVG",           :float,                 :default => 0.0
    t.column "MTRAVG",          :float,                 :default => 0.0
    t.column "COUNTER",         :float,                 :default => 0.0
    t.column "ISSETCHANGE",     :string,  :limit => 20, :default => "0"
    t.column "ISSRINOUTCHANGE", :string,  :limit => 20
    t.column "LOSS",            :string,  :limit => 20
    t.column "CNT",             :float
    t.column "PERCENTAGE",      :float
    t.column "digitno",         :integer
    t.column "charno",          :string,  :limit => 40
    t.column "flag",            :string,  :limit => 1,  :default => "n"
  end

  add_index "machinedatas", ["TRANS_DATE"], :name => "TRANS_DATE"
  add_index "machinedatas", ["CLUSTER_NAME"], :name => "CLUSTER_NAME"
  add_index "machinedatas", ["SHOP_NAME"], :name => "SHOP_NAME"
  add_index "machinedatas", ["GROUP_ID"], :name => "GROUP_ID"
  add_index "machinedatas", ["MACHINE_NO"], :name => "MACHINE_NO"

  create_table "machines", :force => true do |t|
    t.column "ShopName",    :string
    t.column "GroupID",     :string
    t.column "MachineNo",   :string
    t.column "MachineName", :string
    t.column "ClusterName", :string
    t.column "OpeningBal",  :string
    t.column "Multiplyby",  :integer
    t.column "MachineType", :string,  :limit => 50
    t.column "SrateIn",     :string,  :limit => 50
    t.column "SrateOut",    :string,  :limit => 50
    t.column "MrateIn",     :string,  :limit => 50
    t.column "MrateOut",    :string,  :limit => 50
  end

  create_table "previousrecords", :force => true do |t|
    t.column "Date",       :date
    t.column "Xcash",      :integer
    t.column "Xcredit",    :integer
    t.column "ShopName",   :string
    t.column "Openingbal", :integer
  end

  create_table "shops", :force => true do |t|
    t.column "ShopName",    :string
    t.column "Address",     :string
    t.column "ClusterName", :string
    t.column "OpeningBal",  :string
    t.column "Cash",        :integer
    t.column "Credit",      :integer
  end

  create_table "shortreasons", :force => true do |t|
    t.column "McShortReason", :string, :limit => 80
  end

  create_table "tablename1", :id => false, :force => true do |t|
    t.column "name", :string,  :limit => 11
    t.column "no",   :integer, :limit => 50
    t.column "MCno", :string,  :limit => 50
  end

  create_table "users", :force => true do |t|
    t.column "login",       :string,               :default => ""
    t.column "password",    :string
    t.column "firstname",   :string
    t.column "lastname",    :string
    t.column "phoneno",     :string
    t.column "usertype",    :string
    t.column "emailid",     :string
    t.column "userstatus",  :integer,              :default => 0
    t.column "loginstatus", :string,  :limit => 1
  end

end
